"""初始化数据库（UUID主键版）

Revision ID: 4dcdbcf95fa4
Revises: 
Create Date: 2026-01-22 10:57:02.270648

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4dcdbcf95fa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dept',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='部门名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='部门编号'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='父节点id'),
    sa.Column('tree_path', sa.String(length=255), nullable=False, comment='父节点id路径'),
    sa.Column('sort', sa.SmallInteger(), nullable=True, comment='显示顺序'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态(1-正常 0-禁用)'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.UUID(), nullable=True, comment='修改人ID'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除标识(1-已删除 0-未删除)'),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_dept.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id'),
    comment='部门管理表'
    )
    op.create_table('sys_dict',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dict_code', sa.String(length=50), nullable=True, comment='类型编码'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='类型名称'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态(0:正常;1:禁用)'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('update_by', sa.UUID(), nullable=True, comment='修改人ID'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='是否删除(1-删除，0-未删除)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    comment='数据字典类型表'
    )
    op.create_table('sys_dict_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dict_code', sa.String(length=50), nullable=True, comment='关联字典编码，与sys_dict表中的dict_code对应'),
    sa.Column('value', sa.String(length=50), nullable=True, comment='字典项值'),
    sa.Column('label', sa.String(length=100), nullable=True, comment='字典项标签'),
    sa.Column('tag_type', sa.String(length=50), nullable=True, comment='标签类型，用于前端样式展示（如success、warning等）'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态（1-正常，0-禁用）'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('update_by', sa.UUID(), nullable=True, comment='修改人ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    comment='数据字典项表'
    )
    op.create_table('sys_menu',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='父菜单ID（NULL表示顶级菜单）'),
    sa.Column('tree_path', sa.String(length=255), nullable=True, comment='父节点ID路径'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='菜单名称'),
    sa.Column('type', sa.String(length=1), nullable=False, comment='菜单类型（C-目录 M-菜单 B-按钮）'),
    sa.Column('route_name', sa.String(length=255), nullable=True, comment='路由名称（Vue Router 中用于命名路由）'),
    sa.Column('route_path', sa.String(length=128), nullable=True, comment='路由路径（Vue Router 中定义的 URL 路径）'),
    sa.Column('component', sa.String(length=128), nullable=True, comment='组件路径（组件页面完整路径，相对于 src/views/，缺省后缀 .vue）'),
    sa.Column('perm', sa.String(length=128), nullable=True, comment='【按钮】权限标识'),
    sa.Column('always_show', sa.SmallInteger(), nullable=True, comment='【目录】只有一个子路由是否始终显示（1-是 0-否）'),
    sa.Column('keep_alive', sa.SmallInteger(), nullable=True, comment='【菜单】是否开启页面缓存（1-是 0-否）'),
    sa.Column('visible', sa.SmallInteger(), nullable=True, comment='显示状态（1-显示 0-隐藏）'),
    sa.Column('sort', sa.SmallInteger(), nullable=True, comment='排序'),
    sa.Column('icon', sa.String(length=64), nullable=True, comment='菜单图标'),
    sa.Column('redirect', sa.String(length=128), nullable=True, comment='跳转路径'),
    sa.Column('params', sa.String(length=255), nullable=True, comment='路由参数'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    comment='系统菜单表'
    )
    op.create_table('sys_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='角色编码'),
    sa.Column('sort', sa.SmallInteger(), nullable=True, comment='显示顺序'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='角色状态(1-正常 0-停用)'),
    sa.Column('data_scope', sa.SmallInteger(), nullable=True, comment='数据权限(1-所有数据 2-部门及子部门数据 3-本部门数据 4-本人数据)'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人 ID'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.UUID(), nullable=True, comment='更新人ID'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除标识(0-未删除 1-已删除)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='系统角色表'
    )
    op.create_table('sys_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True, comment='用户名'),
    sa.Column('nickname', sa.String(length=64), nullable=True, comment='昵称'),
    sa.Column('gender', sa.SmallInteger(), nullable=True, comment='性别(1-男 2-女 0-保密)'),
    sa.Column('password', sa.String(length=100), nullable=False, comment='密码'),
    sa.Column('dept_id', sa.UUID(), nullable=True, comment='部门ID'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='用户头像'),
    sa.Column('mobile', sa.String(length=20), nullable=True, comment='联系方式'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态(1-正常 0-禁用)'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='用户邮箱'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人ID'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('update_by', sa.UUID(), nullable=True, comment='修改人ID'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除标识(0-未删除 1-已删除)'),
    sa.Column('openid', sa.String(length=28), nullable=True, comment='微信 openid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    comment='系统用户表'
    )
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.create_table('sys_role_menu',
    sa.Column('role_id', sa.UUID(), nullable=False, comment='角色ID'),
    sa.Column('menu_id', sa.UUID(), nullable=False, comment='菜单ID'),
    sa.ForeignKeyConstraint(['menu_id'], ['sys_menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'menu_id'),
    comment='角色菜单关联表'
    )
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.UUID(), nullable=False, comment='角色ID'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    comment='用户角色关联表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_role')
    op.drop_table('sys_role_menu')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_table('sys_role')
    op.drop_table('sys_menu')
    op.drop_table('sys_dict_item')
    op.drop_table('sys_dict')
    op.drop_table('sys_dept')
    # ### end Alembic commands ###
