"""创建权限表、角色-权限表，修改应用层对应查询逻辑。

Revision ID: 5b6f79ed7e6d
Revises: 4dcdbcf95fa4
Create Date: 2026-01-22 19:49:39.569590

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5b6f79ed7e6d'
down_revision = '4dcdbcf95fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='权限名称'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='权限编码'),
    sa.Column('sort', sa.SmallInteger(), nullable=True, comment='显示顺序'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='权限状态(1-正常 0-停用)'),
    sa.Column('data_scope', sa.SmallInteger(), nullable=True, comment='数据权限(1-所有数据 2-部门及子部门数据 3-本部门数据 4-本人数据)'),
    sa.Column('create_by', sa.UUID(), nullable=True, comment='创建人 ID'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_by', sa.UUID(), nullable=True, comment='更新人ID'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.SmallInteger(), nullable=True, comment='逻辑删除标识(0-未删除 1-已删除)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='系统权限表'
    )
    op.create_table('sys_role_permission',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    comment='角色权限关联表'
    )
    op.create_unique_constraint(None, 'sys_dept', ['id'])
    op.create_unique_constraint(None, 'sys_dict', ['id'])
    op.create_unique_constraint(None, 'sys_dict_item', ['id'])
    op.create_unique_constraint(None, 'sys_menu', ['id'])
    op.create_unique_constraint(None, 'sys_role', ['id'])
    op.create_unique_constraint(None, 'sys_user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sys_user', type_='unique')
    op.drop_constraint(None, 'sys_role', type_='unique')
    op.drop_constraint(None, 'sys_menu', type_='unique')
    op.drop_constraint(None, 'sys_dict_item', type_='unique')
    op.drop_constraint(None, 'sys_dict', type_='unique')
    op.drop_constraint(None, 'sys_dept', type_='unique')
    op.drop_table('sys_role_permission')
    op.drop_table('sys_permission')
    # ### end Alembic commands ###
